DROP TABLE IF EXISTS channel_invitation CASCADE;
DROP TABLE IF EXISTS membership CASCADE;
DROP TABLE IF EXISTS message CASCADE;
DROP TABLE IF EXISTS channel CASCADE;
DROP TABLE IF EXISTS registration_invitation CASCADE;
DROP TABLE IF EXISTS auth_token CASCADE;
DROP TABLE IF EXISTS users CASCADE;


DROP TYPE IF EXISTS invite_status CASCADE;
DROP TYPE IF EXISTS membership_role CASCADE;
DROP TYPE IF EXISTS invite_role CASCADE;
